### ISSUE TITLE
grunt-tslint@3.3.0 seems not to be working with tslint@4.0.0

### ISSUE THREAD

**Issue by RachelSatoyama** [palantir/grunt-tslint#60]
**Steps to reproduce:**
- create new  npm project 
- npm install -D typescript tslint grunt-tslint 
- introduce tslint task
- run `grunt tslint`

**A minimal example to reproduce:**

- `git clone https://github.com/RachelSatoyama/bugreport.git`
- `cd bugreport/tslint-versions`
- `npm install`
-  `grunt tslint`

**What happens:**
an error:

> Warning: Linter.findConfiguration is not a function Use --force to continue.
> Aborted due to warnings.
> 

**What expected to happen:**
grunt tslint to be runned (or, alternatively and warning on incompatible peer dependencies to be shown)

**Comment by adidahiya** [comment]
this is also addressed by #56. TSLint v4 is a major version bump with breaking changes; you can expect grunt-tslint v4 to support it.

**Comment by RachelSatoyama** [comment]
Well, I at least can expect some warning during npm install but sure
Thank you again!
